# Generated by Django 4.1.13 on 2024-04-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebateConversations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_ID', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100)),
                ('sender', models.TextField()),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterModelTable(
            name='usersession',
            table='Audiotext',
        ),
    ]
